# Generated by Django 4.2.4 on 2023-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='date_of_death',
            field=models.DateField(blank=True),
        ),
    ]
