# Generated by Django 4.2.4 on 2023-08-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_movie_avg_rating_remove_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='director', to='core.movie'),
        ),
    ]
