# Generated by Django 4.2.4 on 2023-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_director_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
